### ISSUE TITLE
getnextkey: [Error : 651 : not inited]

### ISSUE THREAD

**Issue by FrankWong1213** [awesome-nodes/ton#1]
I  runed full install with your bash commands on Ubuntu 18.04,but there are a lot of error messages as follow:

[ 2][t 3][1571192516.824018478][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 5][1571192518.043049097][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 1][1571192518.801652908][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][1571192519.270365715][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 7][1571192520.497820616][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 4][1571192521.535279036][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 1][1571192522.763339758][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 4][1571192523.557774782][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][1571192523.785084486][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 3][1571192523.941581726][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][1571192524.776961803][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][1571192525.013118505][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 1][1571192525.162747145][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][1571192525.570689917][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][1571192526.215411663][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 3][1571192526.514874935][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][1571192527.050489664][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][1571192527.289118052][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 6][1571192528.508688688][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]
[ 2][t 3][1571192528.732957363][full-node-shard.cpp:380][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][1571192529.702877998][download-state.cpp:227][!downloadstatereq(-1,8000000000000000,489584)]	failed to download state : [Error : 651 : state not found]

**Comment by begetan** [comment]
First of all you shoud wait up to 5 minutes until node start synchronisation with the network. If not, the error may appear in the following cases:

1. Your node has no access to the internet.  Try ping 8.8.8.8 to check it is working.

2. Your configuration file has wrong IP.  Try to check `curl ifconfig.co` and compare with `hostname -I` output. Your node `config.json` should have a public IP address.  You can translate it from decimal signed to hex and convert bytes to IP addreses. I know it is a bit tricky, huh!

3. Test network may have a real issue. Please check https://test.ton.org/testnet/ comuniti chats, etc... for updates.
